[package]
authors = ["michael.mogenson@gmail.com"]
edition = "2018"
readme = "README.md"
name = "trinket-m0"
version = "0.1.0"

[dependencies]
panic-halt = "0.2.0"
cty = "0.2.1"
embedded-hal = { version = "0.2.3", features = ["unproven"] }

[build-dependencies]
cc = "1.0.47"
bindgen = "0.52.0"
